spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect